# Generated by Django 5.2.5 on 2025-08-12 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unvan", models.CharField(max_length=255, verbose_name="Ünvan")),
                (
                    "vergi_no",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Vergi No"
                    ),
                ),
                (
                    "vergi_dairesi",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Vergi Dairesi",
                    ),
                ),
                ("adres", models.TextField(blank=True, null=True)),
                ("telefon", models.CharField(blank=True, max_length=20, null=True)),
                ("eposta", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "bakiye",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "tip",
                    models.CharField(
                        choices=[
                            ("Musteri", "Müşteri"),
                            ("Tedarikci", "Tedarikçi"),
                            ("Diger", "Diğer"),
                        ],
                        default="Diger",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cari Hesap",
                "verbose_name_plural": "Cari Hesaplar",
            },
        ),
        migrations.CreateModel(
            name="GunlukOzet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarih", models.DateField(unique=True)),
                (
                    "baslangic_tutari",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "sistem_nakit_geliri",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "kasadan_cikis_toplami",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "beklenen_nakit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("sayilan_nakit", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fark", models.DecimalField(decimal_places=2, max_digits=10)),
                ("durum", models.CharField(blank=True, max_length=20, null=True)),
                ("aciklama", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Günlük Kasa Özeti",
                "verbose_name_plural": "Günlük Kasa Özetleri",
            },
        ),
        migrations.CreateModel(
            name="Kategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kategori_adi",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Kategori Adı"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ürün Kategorisi",
                "verbose_name_plural": "Ürün Kategorileri",
            },
        ),
        migrations.CreateModel(
            name="Fatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fatura_no",
                    models.CharField(max_length=50, verbose_name="Fatura Numarası"),
                ),
                ("tarih", models.DateField()),
                ("tip", models.CharField(max_length=20, verbose_name="Fatura Tipi")),
                (
                    "ara_toplam",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "kdv_toplam",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "genel_toplam",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("odeme_durumu", models.CharField(default="Ödenmedi", max_length=20)),
                (
                    "efatura_uuid",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "efatura_durum",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "cari",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="muhasebe.cari",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fatura",
                "verbose_name_plural": "Faturalar",
                "ordering": ["-tarih"],
            },
        ),
        migrations.CreateModel(
            name="MuhasebeUrun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barkod", models.CharField(max_length=100, unique=True)),
                ("urun_adi", models.CharField(max_length=255, verbose_name="Ürün Adı")),
                ("birim", models.CharField(default="Adet", max_length=20)),
                (
                    "kdv_orani",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
                ),
                (
                    "alis_fiyati",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "satis_fiyati",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("stok_miktari", models.IntegerField(default=0)),
                (
                    "kategori",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="muhasebe.kategori",
                    ),
                ),
            ],
            options={
                "verbose_name": "Muhasebe Ürünü",
                "verbose_name_plural": "Muhasebe Ürünleri",
            },
        ),
        migrations.CreateModel(
            name="Odeme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarih", models.DateField()),
                ("tutar", models.DecimalField(decimal_places=2, max_digits=10)),
                ("islem_tipi", models.CharField(max_length=20)),
                ("odeme_yontemi", models.CharField(max_length=50)),
                ("aciklama", models.TextField(blank=True, null=True)),
                (
                    "cari",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="muhasebe.cari"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ödeme",
                "verbose_name_plural": "Ödemeler",
            },
        ),
        migrations.CreateModel(
            name="StokHareketi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarih", models.DateTimeField(auto_now_add=True)),
                ("tip", models.CharField(max_length=10, verbose_name="Hareket Tipi")),
                ("miktar", models.IntegerField()),
                ("birim_fiyat", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "fatura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="muhasebe.fatura",
                    ),
                ),
                (
                    "urun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="muhasebe.muhasebeurun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stok Hareketi",
                "verbose_name_plural": "Stok Hareketleri",
                "ordering": ["-tarih"],
            },
        ),
    ]
