# Generated by Django 5.2.5 on 2025-08-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("randevu", "0002_alter_randevu_temsilci"),
    ]

    operations = [
        migrations.AddField(
            model_name="randevu",
            name="status",
            field=models.CharField(
                choices=[("beklemede", "Beklemede"), ("onaylandi", "Onaylandı")],
                default="beklemede",
                max_length=10,
            ),
        ),
    ]
