# Generated by Django 5.2.5 on 2025-08-07 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("randevu", "0003_randevu_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="temsilciprofili",
            name="ozel_gun_notu",
            field=models.CharField(
                blank=True,
                help_text="Doğum günü, evlilik yıldönümü gibi hatırlatıcı notlar.",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="Urun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=255)),
                ("aciklama", models.TextField(blank=True, null=True)),
                (
                    "firma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urunler",
                        to="randevu.firma",
                    ),
                ),
            ],
            options={
                "ordering": ["ad"],
                "unique_together": {("firma", "ad")},
            },
        ),
        migrations.CreateModel(
            name="Teklif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mal_fazlasi_sarti",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Mal Fazlası Şartı (Örn: 10+1, 20+3)",
                    ),
                ),
                (
                    "ekstra_iskonto",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Ekstra İskonto (Örn: Fatura altı %3, Nakit çek)",
                    ),
                ),
                (
                    "eczaci_degerlendirmesi",
                    models.TextField(blank=True, verbose_name="Eczacı Değerlendirmesi"),
                ),
                (
                    "randevu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teklifler",
                        to="randevu.randevu",
                    ),
                ),
                (
                    "urun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="randevu.urun"
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
