# Generated by Django 5.2.5 on 2025-08-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("randevu", "0004_temsilciprofili_ozel_gun_notu_urun_teklif"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="firma",
            options={"verbose_name": "Firma", "verbose_name_plural": "Firmalar"},
        ),
        migrations.AlterModelOptions(
            name="randevu",
            options={
                "ordering": ["tarih_saat"],
                "verbose_name": "Randevu",
                "verbose_name_plural": "Randevular",
            },
        ),
        migrations.AlterModelOptions(
            name="teklif",
            options={
                "ordering": ["-id"],
                "verbose_name": "Teklif",
                "verbose_name_plural": "Teklifler",
            },
        ),
        migrations.AlterModelOptions(
            name="temsilciprofili",
            options={
                "verbose_name": "Temsilci Profili",
                "verbose_name_plural": "Temsilci Profilleri",
            },
        ),
        migrations.AlterModelOptions(
            name="urun",
            options={
                "ordering": ["ad"],
                "verbose_name": "Ürün",
                "verbose_name_plural": "Ürünler",
            },
        ),
        migrations.AddField(
            model_name="temsilciprofili",
            name="sorumlu_oldugu_urunler",
            field=models.ManyToManyField(
                blank=True, to="randevu.urun", verbose_name="Sorumlu Olduğu Ürünler"
            ),
        ),
    ]
