# Generated by Django 5.2.5 on 2025-08-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("randevu", "0005_alter_firma_options_alter_randevu_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="randevu",
            name="status",
            field=models.CharField(
                choices=[
                    ("beklemede", "Beklemede"),
                    ("onaylandi", "Onaylandı"),
                    ("gelinmedi", "Gelinmedi"),
                    ("tamamlandi", "Tamamlandı"),
                ],
                default="beklemede",
                max_length=10,
            ),
        ),
    ]
