# Generated by Django 5.2.5 on 2025-08-17 22:06

import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("randevu", "0006_alter_randevu_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="randevu",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="randevu",
            name="tarih_saat",
            field=models.DateTimeField(unique=True),
        ),
        migrations.AddIndex(
            model_name="randevu",
            index=models.Index(
                fields=["tarih_saat"], name="randevu_ran_tarih_s_9c4312_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="randevu",
            constraint=models.UniqueConstraint(
                django.db.models.functions.datetime.TruncDate("tarih_saat"),
                models.F("temsilci"),
                condition=models.Q(("temsilci__isnull", False)),
                name="uniq_temsilci_per_day",
            ),
        ),
    ]
