# Generated by Django 5.2.5 on 2025-08-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("randevu", "0007_alter_randevu_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="urun",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="urun",
            name="barkod",
            field=models.CharField(
                blank=True,
                help_text="Ürünün benzersiz barkodu",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
